### ISSUE TITLE
Saved Pdf cannot be opened in Acrobat. Links in online pdf do not work.

### ISSUE THREAD

**Issue by JakeKeller** [MicrosoftLearning/CSharpForAbsBeginners#1]
Hi,
firstly, thank you so much for this companion to the c# funamentals course!
I really appreciate you putting all this effort into it. If I find a way I'll definitely try to make it more public. Unfortunately both the old and new pdf seem to be damaged (so Acrobat says) and cannot  be opened. Also, when viewing them on github I cannot click on the provided links, which makes  it difficult to find your repository with the solutions. 

Thanks again for posting this,

Jake

**Comment by gerryaobrien** [comment]
Links in the online preview will not work.  As far as I can tell, that is by design on GitHub.   I have cloned this repository on a local computer and verified that the PDF opens, is readable, is not corrupt, and that links work.

**Comment by JakeKeller** [comment]
Hi Gerry, thanks for responding so quickly.
I figured it out. Save link as (pdf) did not and still does not work. It saves a pdf file which cannot be opened. Must be a github issue, I'm assuming it is saving a somehow corrupted/restricted preview version of the actual pdf.

 However when I download as zip, using the provided button, the pdf file inside the zip is indeed fine and can be opened. I just hadn't tried that before. This just as a hint to anyone else who might be struggling with this.
